name: Windows MSYS2 Build Tools

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  msys2:
    name: >-
      msys2 tools
    #env:
    #  FORCE_UPDATE: true
    runs-on: windows-2022
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy msys2 files to temp dir
        run:  |
          $temp = $env:RUNNER_TEMP
          md $temp\msys64
          # copy current msys2 to temp folder, needed to determine what files to include
          # in zip file (only newer files)
          xcopy C:\msys64 $temp\msys64 /s /q
        timeout-minutes: 15

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ucrt
        timeout-minutes: 7

      - name: Update msys2 tools 7z and Upload
        run:  ruby create_msys2_pkg.rb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 10

  gcc:
    name: >-
      ${{ matrix.gcc }} gcc
    #env:
    #  FORCE_UPDATE: true
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        include:
          - { gcc: mingw64    , ruby: '3.0' }
          - { gcc: mingw64-3.0, ruby: mingw }
          - { gcc: ucrt64     , ruby: 3.1   }
          - { gcc: ucrt64-3.0 , ruby: ucrt  }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
        timeout-minutes: 7

      - name: Update ${{ matrix.gcc }} gcc 7z and Upload
        run:  ruby create_gcc_pkg.rb ${{ matrix.gcc }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 10
